esphome:
  name: ir-remote-transmitter
  friendly_name: ir-remote-transmitter

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret ir-remote-transmitter-api-encryption-key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ir-remote-transmitter-ota-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Ir-Remote-Transmitter"
    password: !secret ir-remote-transmitter-ap-password

# Enable IR transmitter on GPIO15
remote_transmitter:
  pin: GPIO15
  carrier_duty_percent: 50%

button:
  - platform: template
    name: "Heater On/Off"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF00
          command: 0xF00F

  - platform: template
    name: "Show Temp"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF01
          command: 0xED12

  - platform: template
    name: "Heat UP"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF01
          command: 0xE51A

  - platform: template
    name: "Heat DOWN"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xEF01
          command: 0xFA05

  - platform: template
    name: "TV Volume DOWN"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xFC03
