esphome:
  name: garage-door-side-entrance
  friendly_name: Garage Door Side Entrance Controller
  on_boot:
    - priority: -100.0 # At this priority, pretty much everything should already be initialized.
      then:
        # DEVTODO turn off (unlocked) for testing
        # - switch.turn_on: lock_switch
        - switch.turn_off: lock_switch
        - output.turn_on: run_led
rp2040:
  board: rpipicow

# DEVTODO - Delete if not used?
# globals:
#   - id: is_cover_locked
#     type: bool
#     restore_value: no
#     initial_value: 'true'

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Allow Over-The-Air updates  
ota:
  - platform: esphome
    password: !secret ota-password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "GDO Fallback Hotspot"
    password: !secret wifi_password

#
# LEDs
#    
output:
  - platform: gpio
    pin: GPIO9
    id: is_active_led
  
  - platform: gpio
    pin: GPIO11
    id: run_led
  
  - platform: gpio
    pin: GPIO13
    id: lock_led

#
# Buttons
#
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true
    name: "Outdoor Cover Button"
    id: od_cover_button
    on_press:
      then:
        - logger.log: "👉 BUTTON Press - od_cover_button"
        - if:
            condition:
              switch.is_on: lock_switch
            then:
              - logger.log: "❌ IGNORED Press - cover is locked"
            else:
              - logger.log: "✅ Toggle - toggle the cover"
              - homeassistant.service:
                  service: cover.toggle
                  data:
                    entity_id: cover.garage_door_opener_c0f8d0_side_door_garage_door

  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    name: "Indoor Cover Button"
    id: id_cover_button
    on_press:
      then:
        - logger.log: "👉 BUTTON Press - id_cover_button"
        - logger.log: "✅ Toggle - toggle the cover"
        - homeassistant.service:
            service: cover.toggle
            data:
              entity_id: cover.garage_door_opener_c0f8d0_side_door_garage_door

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "Lock Button"
    id: lock_button
    on_press:
      then:
        - logger.log: "👉 BUTTON Press - lock_button"
        - switch.toggle: lock_switch

#
# Switches
#
switch:
  - platform: output
    name: "Lock Switch"
    output: lock_led
    id: lock_switch
    on_turn_on:
      then:
        - logger.log: "🔒 LOCK - lock_switch turned ON"
        - output.turn_on: lock_led
    on_turn_off:
      then:
        - logger.log: "🔒 UNLOCK - lock_switch turned OFF"
        - output.turn_off: lock_led


